### PR TITLE
Support for bibliographies when using recent versions of pandoc

### LINKED ISSUE #8: New Pandoc compains about `cslreferences`
The issue (see https://github.com/bearloga/wmf-product-analytics-report/issues/3) _doesn't_ directly affect {memor} (I've checked). However, if using citation styling in any {memor}-based documents (e.g. https://github.com/bearloga/wmf-product-analytics-report/blob/master/R/pdf.R#L76), that creates problems for recent versions of Pandoc.

The underlying issue is a section that is missing from the TeX template (see https://github.com/mpark/wg21/issues/54#issuecomment-569867462 for more info).

I've forked {memor} and added the missing CSL section there (https://github.com/bearloga/memor/commit/6dd1faaf97eb4df6b64aed1597218a706360c6e0) and that fixed it for my {memor}-based template. I wasn't sure whether to submit a PR since this is a fix for an issue of a derivative package. Please let me know if that would be okay.

### PR DESCRIPTION
**Pull request by bearloga**
Resolves #8 

**P.S.** The version change was for dependency management and ensuring that my {memor}-based template only worked when using the fork that included the fix.

### CODE REVIEW

**Comment by muschellij2** [comment]
Got bit by this as well - @hebrewseniorlife - is recommendation to use this branch until master pulls?

**Comment by haozhu233** [comment]
@muschellij2 @bearloga Sorry for the delay. I will review this and merge it tonight.

**Comment by haozhu233** [comment]
Thank you @bearloga! Sorry for being slow on this. I will push it to CRAN tonight.

**Comment by bearloga** [comment]
No worries! :D Thanks @haozhu233!

**Pull request merged**
